### ISSUE TITLE
"views" test expects different data from the exercise.

### ISSUE THREAD

**Issue by Pomax** [hapijs/makemehapi#122]
The exercise asks
```
Create a server which responds to requests to /?name=Handling using a template
located at templates/index.html which outputs the following HTML:

    <html>
        <head><title>Hello Handling</title></head>
        <body>
            Hello Handling
        </body>
    </html>
```

When verifying the program output, it actually expects "Hello Handling Test", although it isn't clear why. If the idea is to have a {{name}} templating substitution, the exercise text probably needs to be changed to reflect that (as is, the output requested doesn't seem particularly related to templating in any way)

**Comment by lloydbenson** [comment]
Not sure why this would have caused any problem for you, but I think the solution here is addressed in:

https://github.com/hapijs/makemehapi/pull/123

It would be helpful to verify quick by making this quick change locally and see if you see better results.  If that looks good I'll get this merged in.

**Comment by Pomax** [comment]
not a problem as such, adding the word "Test" made the verifier pass of course, but there was a mismatch between "the assignment" and "what it verified" so that's always good to fix. The patch indeed fixes the problem, although the assignment still doesn't mention that it wants the word "Handling" to be templated in, so that might still be an incompletion in the assignment text.

**Comment by lloydbenson** [comment]
Glad this fixed the initial issue.  As far as the assignment not mentioning the word Handling:

https://github.com/hapijs/makemehapi/blob/master/exercises/views/problem.md

At the very top it says to use that as the query string.  Not sure what you mean by templated in, it just passes this word in.  Can you clarify a bit more what you mean?

**Comment by Pomax** [comment]
it says to use it as query string, but it doesn't say to use that query argument in the template. The assignment shows the "desired HTML", so if someone's copy-pasting the hints, which they will be, there is nothing in the hint code to suggest a {{name}} is needed. "generate the HTML, done, not sure how this involves templating in any way".

Of course those of us already familiar with mustache/jinja/nunjucks/etc know what is required, but there will be a substantial group for whom this is their first exposure to templating, and the exercise forgets to explicitly say "use a {{name}} templating placeholder" or something similar.

**Comment by lloydbenson** [comment]
Great, this explanation helps a bit more.  Feel free to PR a more helpful problem.md with improvements in wording to make that more clear.  If you don't want to do that, I'll let @nvcexploder think about providing more clarity.  Do you mind opening a new issue for that?

**Comment by Pomax** [comment]
will do.

**Comment by lloydbenson** [comment]
Thanks alot for your generous feedback.  It is greatly appreciated.
